// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesGI0Yje0OJZxj1oJmtvJKkB-W32aAPk',
    appId: '1:902767199804:web:909ed38a75baed6635e539',
    messagingSenderId: '902767199804',
    projectId: 'flutter-firebase-2ea1a',
    authDomain: 'flutter-firebase-2ea1a.firebaseapp.com',
    storageBucket: 'flutter-firebase-2ea1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_AgoMTpJlkhbeeTvha577jq5S4OkJ_5o',
    appId: '1:902767199804:android:201c53216cda45a635e539',
    messagingSenderId: '902767199804',
    projectId: 'flutter-firebase-2ea1a',
    storageBucket: 'flutter-firebase-2ea1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoPDMNHs3s_dzWft5PXIw__3bW-liXZk',
    appId: '1:902767199804:ios:6d25dfcb15e82d0635e539',
    messagingSenderId: '902767199804',
    projectId: 'flutter-firebase-2ea1a',
    storageBucket: 'flutter-firebase-2ea1a.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEoPDMNHs3s_dzWft5PXIw__3bW-liXZk',
    appId: '1:902767199804:ios:01053c11815a157135e539',
    messagingSenderId: '902767199804',
    projectId: 'flutter-firebase-2ea1a',
    storageBucket: 'flutter-firebase-2ea1a.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
